name: gpr_coffee_shop
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1+1 # زيادة الإصدار من 1.0.0+1 إلى 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  reorderable_grid_view: ^2.2.8
  cupertino_icons: ^1.0.6
  get: ^4.6.5
  get_storage: ^2.1.1 #  get_storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  fl_chart: ^0.65.0
  image_picker: ^1.0.4 # لاختيار الصور
  image: ^4.0.17 # لمعالجة الصور
  path_provider: ^2.0.15 # للحصول على المسارات
  google_fonts: ^4.0.4
  shimmer: ^3.0.0
  flutter_neumorphic_plus: ^3.3.0
  url_launcher: ^6.1.10
  carousel_slider: ^4.2.1
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  path: ^1.8.3
  qr_flutter: ^4.1.0
  json_annotation: ^4.9.0
  photo_view: ^0.14.0
  shared_preferences: ^2.2.0
  share_plus: ^7.2.1
  logger: ^2.0.2
  intl: ^0.18.0 #  for date/time formatting
  cached_network_image: ^3.3.0 # إضافة مكتبة تخزين الصور مؤقتاً من الإنترنت
  transparent_image: ^2.0.1 # إضافة مكتبة صور شفافة للتحميل المتدرج
  google_maps_flutter: ^2.5.2 # إضافة مكتبة خرائط جوجل
  flutter_image_compress: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
 
    - assets/images/JBRbg.png
    - assets/images/JBRbg2.png
    - assets/images/JBRTbg.png
    - assets/images/logo.png
    - assets/images/logo1.png
    - assets/images/logo2.png
    - assets/images/logo3.png
    - assets/images/logo4.png
    - assets/images/logo6.png
    - assets/images/logo5.png
    - assets/images/logo7.png
    - assets/images/logo8.png
    - assets/images/placeholder.png
    - assets/images/splash_video.mp4
    - assets/images/bahrain_flag.png
    - assets/images/splash_screen.gif

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
